spring.application.name=InventoryService

spring.config.import=optional:configserver:http://config-server:8888

spring.datasource.url=  jdbc:postgresql://inventory-db:5432/inventoryDB
spring.datasource.username=postgres
spring.datasource.password=data@2601
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka

