

services:
  zipkin:
    image:  openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      - POSTGRES_DB=orderDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=data@2601
    networks:
      - ecommerce-network
    volumes:
      - order-db-data:/var/lib/postgresql/data


  inventory-db:
    image: postgres:16
    container_name: inventory-db
    environment:
      - POSTGRES_DB=inventoryDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=data@2601
    networks:
      - ecommerce-network
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  config-server:
    image: heydev001/config-server
    container_name: config-server
    networks:
      - ecommerce-network
    depends_on:
      - discovery-service

  discovery-service:
    image: heydev001/discovery-service
    container_name: discovery-service
    networks:
      - ecommerce-network


  api-gateway:
    image: heydev001/api-gateway
    container_name: api-gateway
    networks:
      - ecommerce-network
    depends_on:
      - discovery-service
      - config-server
    ports:
      - "8080:8080"
    restart: always

  inventory-service:
    image: heydev001/inventory-service
    container_name: inventory-service
    networks:
      - ecommerce-network
    depends_on:
      - discovery-service
      - config-server
      - zipkin
      - inventory-db

  order-service:
    image: heydev001/order-service
    container_name: order-service
    networks:
      - ecommerce-network
    depends_on:
      - discovery-service
      - config-server
      - zipkin
      - order-db

volumes:
  order-db-data:
  inventory-db-data:


networks:
  ecommerce-network:

