spring.application.name=OrderService

spring.datasource.url=  jdbc:postgresql://order-db:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=data@2601
spring.jpa.hibernate.ddl-auto=create-drop

spring.config.import=optional:configserver:http://config-server:8888

my.variable = rishi bende
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka